version: "3.8"

services:
  frontend:

    restart: unless-stopped
    #container_name: frontend
    image: aabishkhan/moviereview-application:aabish_fe
    ports:
      - 8900:80
    depends_on: 
      - backend
    environment:
      VITE_REACT_APP_BASEURL: http://aabish.uek.dev.noseryoung.ch:28000
      #:28000
  backend:

    restart: unless-stopped
    #container_name: backend
    image: aabishkhan/moviereview-application:aabish_be
    ports:
      - 28000:8080
    depends_on:
      - db
  db:

    restart: unless-stopped
    image: postgres:15
    #container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres